# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbee9a289769a706aa35aa4dbc38c89bddc9fa6cdfea795b9116a1a6410afaa7b2f76fd9e9c93d7d12982bc22b21f5b3e56375395fbffebda1ee3fd38583301c

test:
  secret_key_base: 1c9c8fe6b89221e05ecf3ec20b10a050d7d07e5a62c01953270738405f76a115821e38a74c4ff5c417b1af1bfadf2060c45659e84383ec518d0977f8aeb13d3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
